# 베이스 이미지
FROM openjdk:8-jdk-alpine

#환경 변수 설정
#설정 파일 경로 설정
#ENV DEVPATH /home/lyae/dev
#워크디렉토리 설정 #이미지에서 적용할 워크 디렉토리임!
#WORKDIR $DEVPATH

LABEL maintainer "lyae <lyaesley@naver.com>"
LABEL title="lyae/was"
LABEL version="1.0"
LABEL description="was"

#VOLUME /tmp
ADD /app/app.war app.war
RUN apk add --no-cache bash
RUN bash -c 'touch /app.war'
#ENTRYPOINT ["java","-jar","-Dspring.profiles.active=prod","/app.war"]

# 포트 지정
EXPOSE 9090
