version: '3.7'
services:
  #ubuntu nginx  config
  nginx:
    container_name: lyae-nginx
    build:
      context: . 
      dockerfile: Dockerfile-ubuntu-nginx
    image:
      lyae/nginx:1.0
    ports:
      - "8888:80"
    expose:
      - "80"
    depends_on:
      - jenkins     
      - portainer
      - was
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /images:/images
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - web
     
  jenkins:
    container_name: lyae-jenkins
    build:
      context: .
      dockerfile: Dockerfile-jenkins-blueocean
    user: root
    image:
        lyae/jenkins-blueocean:1.0
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/lyae/dev/docker_lyae_web/jenkins_home:/var/jenkins_home
      - /home/lyae/dev/docker_lyae_web/app:/home/lyae/dev/docker_lyae_web/app
      - /home/lyae/dev/docker_lyae_web:/home/lyae/dev/docker_lyae_web
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      #- /home/lyae/dev/war:/home/lyae/dev/war
    networks:
      - web
      
  was:
    container_name: lyae-was
    build:
      context: .
      dockerfile: Dockerfile-was
    #user: root
    image:
        lyae/was:1.0
    ports:
      - "9090:9090"
    expose:
      - "9090"
    volumes:
      - /home/lyae/dev/docker_lyae_web/app:/home/lyae/dev/docker_lyae_web/app
      - /images:/images
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - web
    
  portainer:
    container_name: lyae-portainer
    image : portainer/portainer:latest
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - web
        
networks:
  web:
    driver: bridge
    
