# 베이스 이미지
FROM jenkinsci/blueocean:latest

#환경 변수 설정
#설정 파일 경로 설정
#ENV DEVPATH /home/lyae/dev
#워크디렉토리 설정 #이미지에서 적용할 워크 디렉토리임!
#WORKDIR $DEVPATH

USER root

LABEL maintainer "lyae <lyaesley@naver.com>"
LABEL title="lyae/jenkins-blueocean"
LABEL version="1.0"

#docker-compose 컨네이터로 설치
#RUN curl -L --fail https://github.com/docker/compose/releases/download/1.24.0/run.sh -o /usr/local/bin/docker-compose
#RUN chmod +x /usr/local/bin/docker-compose

#이미지에 환경 설정 추가 #메인OS 경로는 Dockerfile 하위를 지정해야함 
#ADD jenkins_home /var/jenkins_home

# 포트 지정
EXPOSE 8080
