# 베이스 이미지
FROM ubuntu:18.04

# Nginx 설치
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install nginx
RUN useradd --no-create-home nginx

#외부설정파일은 아래처럼 copy or add 하면됨 
COPY nginx/nginx.conf /etc/nginx/nginx.conf
# WORKDIR /usr/local/tomcat/bin

# 포트 지정
EXPOSE 80

# 서버 실행
CMD ["nginx", "-g", "daemon off;"]

