version: '3.7'
services:
  #ubuntu nginx  config
  nginx:
    container_name: lyae-nginx
    build:
      context: . 
      dockerfile: Dockerfile-ubuntu-nginx
    image:
      lyae/nginx:2.0
    ports:
      - "8888:80"
    expose:
      - "80"
    depends_on:
      - jenkins     
      - portainer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web
     
  jenkins:
    container_name: lyae-jenkins
    build:
      context: .
      dockerfile: Dockerfile-jenkins-blueocean
    user: root
    image:
        lyae/jenkins-blueocean:1.0
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - /home/lyae/dev/docker_lyae_web/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    
  portainer:
    container_name: lyae-portainer
    image : portainer/portainer:latest
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
        
networks:
  web:
    
